In [50]:
import numpy as np
import random

In [51]:
N = 6
D = 10
K = 4
reg = 0.001

In [52]:
X = np.random.randn(N, D)
y = [random.choice(range(K)) for _ in range(N)]
print(x)
print(y)

[[-2.13890553  0.18847551 -0.4207456  -0.9684808   0.78266339 -1.43311823
  -0.96834831  0.91851453  1.77131695  0.69453329]
 [-0.65802903 -0.329585   -0.55068889  0.40895167 -2.61717952 -0.3072905
   0.28092368  2.03445681 -0.32605587  1.28066922]
 [ 1.17026119  0.45197821  0.32235943  0.47363539  0.5523032  -1.39076295
   1.61576147  0.11378152  0.0170978   1.16600772]
 [-0.358063   -0.0331604   0.90922674  0.3889358   1.61494418  1.13822952
   0.24420246  0.61927065  0.3823539  -0.40211297]
 [ 0.83518475 -0.77238993  0.82524398  0.1769663  -0.07668824 -1.5993572
   1.10744992 -0.56725058  1.14122866 -0.71634278]
 [ 0.71587813 -0.05414087 -0.25794831 -1.0810077  -0.8607779   1.68595415
   1.10029267 -0.3864075  -0.7007725   0.27731918]]
[3, 2, 1, 3, 0, 1]


In [166]:
np.random.seed(123)
W = np.random.randn(D, K)
scores = X.dot(W)
exp_scores = np.exp(scores)
probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
probs

array([[8.05165467e-01, 1.49572772e-01, 3.57788488e-02, 9.48291154e-03],
       [1.03430701e-01, 1.91765789e-01, 4.84495423e-05, 7.04755061e-01],
       [1.41344779e-02, 9.67168358e-01, 5.07205970e-03, 1.36251044e-02],
       [8.83352873e-03, 1.60325293e-02, 2.64209915e-05, 9.75107521e-01],
       [5.70450261e-07, 2.53337160e-03, 9.97463338e-01, 2.71956901e-06],
       [1.38074311e-02, 1.25155605e-05, 9.84186201e-01, 1.99385248e-03]])

## Vectorized

In [156]:
dscores = probs
dscores[range(N), y] -= 1
dscores /= N
dscores

array([[ 1.34194245e-01,  2.49287954e-02,  5.96314147e-03,
        -1.65086181e-01],
       [ 1.72384502e-02,  3.19609648e-02, -1.66658592e-01,
         1.17459177e-01],
       [ 2.35574632e-03, -5.47194034e-03,  8.45343283e-04,
         2.27085073e-03],
       [ 1.47225479e-03,  2.67208821e-03,  4.40349858e-06,
        -4.14874650e-03],
       [-1.66666572e-01,  4.22228600e-04,  1.66243890e-01,
         4.53261501e-07],
       [ 2.30123852e-03, -1.66664581e-01,  1.64031033e-01,
         3.32308746e-04]])

In [157]:
dW = X.T.dot(dscores)
dW += reg * W
dW

array([[-0.15757917, -0.09003765,  0.33723153, -0.09092632],
       [ 0.05157652,  0.33813746, -0.36632435, -0.02517239],
       [ 0.27602942, -0.13895805, -0.16014345,  0.02269768],
       [ 0.39153984, -0.12869345, -0.16006308, -0.10280917],
       [ 0.14289062,  0.17564488, -0.17476029, -0.13799225],
       [ 0.22735523,  0.01845562, -0.28272037,  0.03937762],
       [-0.37275492, -0.08362882,  0.4042006 ,  0.04976993],
       [-0.13033944, -0.06690754,  0.38087059, -0.18767965],
       [-0.01294476, -0.10060145,  0.20460141, -0.09277279],
       [-0.02169277,  0.14725722, -0.60722865,  0.48175936]])

## Numerical

In [167]:
for i in range(N):
  scores = X[i].dot(W) # [1 * num_classes]
  scores -= np.max(scores)

  exp_scores = np.exp(scores)
  probs = exp_scores / np.sum(exp_scores)
  loss += -np.log(probs[y[i]])

  for k in range(K):
    probs[i, y[i]] -= 1
    dW[:, k] += probs[i] *

dW /= N
dW += reg * W
dW

array([[-0.18909489,  0.40496911, -0.19100537, -0.12465693],
       [-0.18848123,  0.40576471, -0.19427448, -0.12336246],
       [-0.18626222,  0.40273104, -0.19217202, -0.12296022],
       [-0.1859888 ,  0.40300469, -0.19189014, -0.12337092],
       [-0.18513758,  0.40640306, -0.1901529 , -0.12238718],
       [-0.18689771,  0.40556388, -0.19248342, -0.12143519],
       [-0.18930216,  0.4030072 , -0.19025476, -0.12456028],
       [-0.18795955,  0.40273882, -0.19165058, -0.12621007],
       [-0.18991433,  0.40293223, -0.19023532, -0.12305782],
       [-0.18778534,  0.40460411, -0.19242398, -0.12249475]])

In [168]:
x

array([[-2.13890553,  0.18847551, -0.4207456 , -0.9684808 ,  0.78266339,
        -1.43311823, -0.96834831,  0.91851453,  1.77131695,  0.69453329],
       [-0.65802903, -0.329585  , -0.55068889,  0.40895167, -2.61717952,
        -0.3072905 ,  0.28092368,  2.03445681, -0.32605587,  1.28066922],
       [ 1.17026119,  0.45197821,  0.32235943,  0.47363539,  0.5523032 ,
        -1.39076295,  1.61576147,  0.11378152,  0.0170978 ,  1.16600772],
       [-0.358063  , -0.0331604 ,  0.90922674,  0.3889358 ,  1.61494418,
         1.13822952,  0.24420246,  0.61927065,  0.3823539 , -0.40211297],
       [ 0.83518475, -0.77238993,  0.82524398,  0.1769663 , -0.07668824,
        -1.5993572 ,  1.10744992, -0.56725058,  1.14122866, -0.71634278],
       [ 0.71587813, -0.05414087, -0.25794831, -1.0810077 , -0.8607779 ,
         1.68595415,  1.10029267, -0.3864075 , -0.7007725 ,  0.27731918]])

In [169]:
np.argmax(x, axis = 1)

array([8, 7, 6, 4, 8, 5], dtype=int64)

In [176]:
x = {}
x[(3, 4)] = 0
x[(1, 5)] = 1
x

{(3, 4): 0, (1, 5): 1}

In [179]:
x = 1
y = x
x = 2
print(x)
print(y)

2
1


In [180]:
x = [1, 2]
y = np.array([1, 2])
print(x * 2)
print(y * 2)

[1, 2, 1, 2]
[2 4]
